### PR TITLE
Guess the default thread count setting from hardware

### PR DESCRIPTION
**Pull request by jej**
Set automatically a default thread count value based on real hardware abilities.
As suggested here to get the value: https://stackoverflow.com/questions/150355/programmatically-find-the-number-of-cores-on-a-machine
Tested on Linux.
My 2 cents contribution :)

### CODE REVIEW

**Comment by jej** [comment]
Note:
"prior to C++11, there's no portable way": I didn't check if flacon is C++11.

**Comment by SokoloffA** [comment]
Thanks for the pull request, it can be done much easier in Qt - https://doc.qt.io/qt-5/qthread.html#idealThreadCount

The problem is I'm not sure that the optimal number of encoders is equal to the number of processor cores. The encoding speed is highly dependent on IO of the disk system and input and output formats. For example, FLAC required much less CPU than lame. I wrote this code 10 years ago, then processors had few cores, but in my tests 6-8 threads were optimal.

Although the number of cores may be suitable as a starting point. Let's do this like:
```
setDefaultValue(Encoder_ThreadCount, qMax(8, QThread::idealThreadCount()));
```

**Comment by jej** [comment]
Yes I agree the real count is not evident... For me with 4 cores but running 8 threads, I have a huge load average and some lag on others applications. With 4 it's ok. As you say, I guess that it's still better to propose the same thread number as cores, because 8 for 4 cores is maybe acceptable but 8 for 1 or 2 cores is probably a pain!

**Comment by jej** [comment]
Oups, I didn't your qMax. Why do you suggest to bound to 8?

**Comment by SokoloffA** [comment]
> Why do you suggest to bound to 8?

The threads are allocated as:
One or more are reserved for the splitter   
```
int count         = mData->threadCount;
int splitterCount = qMax(1.0, ceil(count / 2.0));
```
https://github.com/flacon/flacon/blob/master/converter/converter.cpp#L286

The rest are used for decoding, encoding, replay gain calculating

Therefore, one thread will work inefficiently, the encoder for the first track will wait until the splitter finished the last track.
Also note that the documentation says ["QThread::idealThreadCount() function returns 1 if the number of processor cores could not be detected"](https://doc.qt.io/qt-5/qthread.html#idealThreadCount).
Thus, the **minimum number of threads should be 2**.

I thought that 2 is too small for modern computers. As I said 10 years ago, I tried different options, and for APE->FLAC, 6-8 threads were optimal. But I'm not saying it's suitable for everyone. If you say that 8 is too much, I'm ready to agree. 

2 is too little, 8 is too much, **let's use 4**?

Just for my curiosity. What are your input and output formats? Do you use HDD or SSD?

**Comment by jej** [comment]
Ok thanks for the details. So now you decide, you are the boss for that! :)

I split FLAC+cue to FLAC, on a HDD/usb3

**Pull request merged**
